name: RemoteController
main: hide92795.bukkit.plugin.remotecontroller.RemoteController
version: 1.7.2_3
description: RemoteController
author: hide92795
softdepend: [dynmap]

commands:
  remotecontroller:
    permission: remotecontroller
    aliases: [rc]
  remotecontroller-user:
    permission: remotecontroller.user
    aliases: [rcu]
  remotecontroller-reload:
    permission: remotecontroller.reload
    aliases: [rcr]
  remotecontroller-summon:
    permission: remotecontroller.summon
    aliases: [rcs]